

[build]
  base = "."
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20.19.3"

[[plugins]]
  package = "@netlify/plugin-cache-core"

  [plugins.inputs]
    paths = []

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
