[build]
  base = "."
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20.19.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

